# Transform and clean data from World Bank

### data from the ZIP file source : https://datacatalog.worldbank.org/search/dataset/0037712/World-Development-Indicators

because of the large size of the file, we need to use the long data filtred by indicator, country, of years

1) extract data from sheet : data
2) unpivot the data and use years as long
3) drop NAN values

4) FILTER the data
     - filter the years
        3 options : 1 must be selected (1, 2 or 3)
       
     - filter the countries
        from xls file : Resources_external\selection_countries.xlsx
     - filter the indicators
        from xls file : Resources_external\selection_indicators.xlsx

extract indicators : filter of needed indicators and their assignment to categories




10) generate a csv file for each category of indicators

In [1]:
import pandas as pd

In [2]:
# import data

path = '../Resources_external/WDI_EXCEL_2025_01_28.xlsx'
sheet  = 'Data'
data_df = pd.read_excel(path, sheet_name=sheet )

data_df.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,17.488497,18.001597,18.558234,19.043572,19.586457,20.192064,20.828814,21.372164,22.100884,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.811504,7.096003,7.406706,7.666648,8.020952,8.403358,8.718306,9.097176,9.473374,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.152090,38.488233,38.779953,39.068462,39.445526,39.818645,40.276374,40.687817,41.211606,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.871956,33.922276,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.742043,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,17.672943,16.527554,24.627753,25.432092,27.061929,29.154282,31.022083,32.809138,33.760782,NaN

In [3]:
data_df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023'],
      dtype='object')

In [53]:
shape_original = data_df.shape

# unpivot and get the years as a column

data_lg_df = pd.melt(
                    data_df, 
                    id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],
                    value_vars=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
                                '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
                                '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
                                '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
                                '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
                                '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
                                '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
                                '2023'],
                     var_name='years' ,           
                     value_name='Value' )

shape_unpivot = data_lg_df.shape

# drop NAN values

data_lg_df  = data_lg_df.dropna(how='any')

#rename some columns

data_lg_df  = data_lg_df.rename(columns={
                                        'Country Name' : 'country'  , 
                                        'Indicator Name' : 'indicator'
                                        })

## convert years to int

data_lg_df = data_lg_df.astype({'years' : 'int32'})

## rest index (in case we need to create a dataBase)
data_lg_df = data_lg_df.reset_index()

shape_cleanna = data_lg_df.shape

data_lg_df.head()

,index,country,Country Code,indicator,Indicator Code,years,Value
0,50,Africa Eastern and Southern,AFE,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1960,135.793291
1,56,Africa Eastern and Southern,AFE,Age dependency ratio (% of working-age populat...,SP.POP.DPND,1960,88.967697
2,57,Africa Eastern and Southern,AFE,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,1960,5.631542
3,58,Africa Eastern and Southern,AFE,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,1960,82.969998
4,84,Africa Eastern and Southern,AFE,Aquaculture production (metric tons),ER.FSH.AQUA.MT,1960,380.000000

In [54]:
print(f'shape_oringinal : {shape_original}')
print(f'shape_unpivot : {shape_unpivot}')
print(f'shape_cleanna : {shape_cleanna}')

shape_oringinal : (397936, 68)
shape_unpivot : (25467904, 6)
shape_cleanna : (8888933, 7)

## filter the data

### filter the years

Select the right option

In [55]:
# # choose one option of filter years
    # 1 = 'filter from year x'
    # 2 = 'filter from year x to year Y'
    # 3 = 'filter serie of years'

selection_type = 1

data_filtred = data_lg_df.copy()

# define needed variables
year_st = 1960
year_end = 2025
year_serie = [
                2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
                2023]


if selection_type == 1 : 
                lib_years = f'from_{year_st}'   # to be included in the file name
                date = (data_filtred['years']>year_st)
                data_filtred = data_filtred[date]    

elif selection_type == 2 :

                lib_years = f'btween_{year_st}_{year_end}'   # to be included in the file name
                date = (data_lg_df['years']>year_st) & (data_lg_df['years']<year_end)
                data_filtred = data_filtred[date] 

elif selection_type == 3 :
                lib_years = f'{len(year_serie)}_years_btween_{min(year_serie)}_{max(year_serie)}'    # to be included in the file name
                date = (data_lg_df['years'].isin(year_serie)) 
                data_filtred = data_filtred[date] 


data_filtred.head()

,index,country,Country Code,indicator,Indicator Code,years,Value
37861,397986,Africa Eastern and Southern,AFE,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1961,136.888217
37862,397992,Africa Eastern and Southern,AFE,Age dependency ratio (% of working-age populat...,SP.POP.DPND,1961,89.322284
37863,397993,Africa Eastern and Southern,AFE,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,1961,5.607333
37864,397994,Africa Eastern and Southern,AFE,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,1961,83.310133
37865,397996,Africa Eastern and Southern,AFE,Agricultural land (% of land area),AG.LND.AGRI.ZS,1961,40.488452

## filter the countries

In [56]:
# import indicators selection

path = "../Resources_external/selection_countries.xlsx"
select_countries = pd.read_excel(path)

## filter the selected indicators
x = (select_countries['select'] == 'y')
select_countries = select_countries[x]
## drop column 'select'
select_countries = select_countries.drop(columns = {'select'})

lib_countries = len(select_countries['country'].unique())
select_countries.head(5)

,country,iso3Code,iso2Code,region,continent,sub-region,capitalCity,longitude,latitude
0,Aruba,ABW,AW,Latin America & Caribbean,Latin America & Caribbean,NaN,Oranjestad,-70.0167,12.51670
1,Afghanistan,AFG,AF,South Asia,Asia,NaN,Kabul,69.1761,34.52280
2,Angola,AGO,AO,Sub-Saharan Africa,Africa,Central Africa,Luanda,13.2420,-8.81155
3,Albania,ALB,AL,Europe & Central Asia,Europe,NaN,Tirane,19.8172,41.33170
4,Andorra,AND,AD,Europe & Central Asia,Europe,NaN,Andorra la Vella,1.5218,42.50750

In [57]:
# filter with selected countries
data_filtred = pd.merge(data_filtred, select_countries, on='country')
print(data_filtred.shape)

(7329242, 15)

## filter the indicators

In [58]:
# import indicators selection

path = "../Resources_external/selection_indicators_population.xlsx"
select_indicators = pd.read_excel(path)

## filter the selected indicators
x = (select_indicators['select'] == 'y')
select_indicators = select_indicators[x]
## drop column 'select'
select_indicators = select_indicators.drop(columns = {'select'})

lib_indicators = len(select_indicators['indicator'].unique())
select_indicators.head(5)

,indicator,Indicator Code,Category
1016,"Population ages 00-04, female (% of female pop...",SP.POP.0004.FE.5Y,population
1017,"Population ages 00-04, male (% of male populat...",SP.POP.0004.MA.5Y,population
1018,Population ages 0-14 (% of total population),SP.POP.0014.TO.ZS,population
1019,"Population ages 0-14, female",SP.POP.0014.FE.IN,population
1020,"Population ages 0-14, female (% of female popu...",SP.POP.0014.FE.ZS,population

In [59]:
# filter with selected indicators
data_filtred = pd.merge(data_filtred, select_indicators, on='indicator')
print(data_filtred.shape)

(724273, 17)

In [60]:
data_filtred.head()

,index,country,Country Code,indicator,Indicator Code_x,years,Value,iso3Code,iso2Code,region,continent,sub-region,capitalCity,longitude,latitude,Indicator Code_y,Category
0,472263,Afghanistan,AFG,"Population ages 00-04, female (% of female pop...",SP.POP.0004.FE.5Y,1961,1.768051e+01,AFG,AF,South Asia,Asia,NaN,Kabul,69.1761,34.5228,SP.POP.0004.FE.5Y,population
1,472264,Afghanistan,AFG,"Population ages 00-04, male (% of male populat...",SP.POP.0004.MA.5Y,1961,1.674841e+01,AFG,AF,South Asia,Asia,NaN,Kabul,69.1761,34.5228,SP.POP.0004.MA.5Y,population
2,472265,Afghanistan,AFG,Population ages 0-14 (% of total population),SP.POP.0014.TO.ZS,1961,4.202859e+01,AFG,AF,South Asia,Asia,NaN,Kabul,69.1761,34.5228,SP.POP.0014.TO.ZS,population
3,472266,Afghanistan,AFG,"Population ages 0-14, female",SP.POP.0014.FE.IN,1961,1.924660e+06,AFG,AF,South Asia,Asia,NaN,Kabul,69.1761,34.5228,SP.POP.0014.FE.IN,population
4,472267,Afghanistan,AFG,"Population ages 0-14, female (% of female popu...",SP.POP.0014.FE.ZS,1961,4.336382e+01,AFG,AF,South Asia,Asia,NaN,Kabul,69.1761,34.5228,SP.POP.0014.FE.ZS,population

In [61]:
data_filtred.columns

Index(['index', 'country', 'Country Code', 'indicator', 'Indicator Code_x',
       'years', 'Value', 'iso3Code', 'iso2Code', 'region', 'continent',
       'sub-region', 'capitalCity', 'longitude', 'latitude',
       'Indicator Code_y', 'Category'],
      dtype='object')

In [62]:
data_filtred = data_filtred.drop(columns=['Country Code', 'Indicator Code_x',
       'iso2Code', 'region', 'capitalCity', 'Category'
       ])
data_filtred = data_filtred.rename(columns={'Indicator Code_y' : 'Indicator Code'})
    

data_filtred = data_filtred[['index','country', 'indicator','Indicator Code', 'years', 'Value']]


data_filtred

,index,country,indicator,Indicator Code,years,Value
0,472263,Afghanistan,"Population ages 00-04, female (% of female pop...",SP.POP.0004.FE.5Y,1961,1.768051e+01
1,472264,Afghanistan,"Population ages 00-04, male (% of male populat...",SP.POP.0004.MA.5Y,1961,1.674841e+01
2,472265,Afghanistan,Population ages 0-14 (% of total population),SP.POP.0014.TO.ZS,1961,4.202859e+01
3,472266,Afghanistan,"Population ages 0-14, female",SP.POP.0014.FE.IN,1961,1.924660e+06
4,472267,Afghanistan,"Population ages 0-14, female (% of female popu...",SP.POP.0014.FE.ZS,1961,4.336382e+01
...,...,...,...,...,...,...
724268,25467479,Zimbabwe,"Population ages 75-79, female (% of female pop...",SP.POP.7579.FE.5Y,2023,6.606862e-01
724269,25467480,Zimbabwe,"Population ages 75-79, male (% of male populat...",SP.POP.7579.MA.5Y,2023,4.770122e-01
724270,25467481,Zimbabwe,"Population ages 80 and above, female (% of fem...",SP.POP.80UP.FE.5Y,2023,5.671102e-01
724271,25467482,Zimbabwe,"Population ages 80 and above, male (% of male ...",SP.POP.80UP.MA.5Y,2023,3.391817e-01
724272,25467495,Zimbabwe,"Population, total",SP.POP.TOTL,2023,1.634082e+07

### create new indicators for population
cumulate male + female data

In [63]:
new_df = data_filtred.pivot_table(index=['country', 'years'], columns='indicator', values='Value')
new_df

indicator          Population ages 0-14 (% of total population)  \
country     years
Afghanistan 1961                                      42.028588
            1962                                      42.112814
            1963                                      42.235952
            1964                                      42.409539
            1965                                      42.642237
...                                                         ...
Zimbabwe    2019                                      42.542258
            2020                                      42.183799
            2021                                      41.871925
            2022                                      41.611543
            2023                                      41.323284

indicator          Population ages 0-14, female  \
country     years
Afghanistan 1961                      1924660.0
            1962                      1966249.0
            1963                      2010389.0
            1964                      2059281.0
            1965                      2115680.0
...                                         ...
Zimbabwe    2019                      3231890.0
            2020                      3257229.0
            2021                      3288366.0
            2022                      3322914.0
            2023                      3354429.0

indicator          Population ages 0-14, female (% of female population)  \
country     years
Afghanistan 1961                                           43.363823
            1962                                           43.335269
            1963                                           43.320036
            1964                                           43.363290
            1965                                           43.508184
...                                                              ...
Zimbabwe    2019                                           40.258090
            2020                                           39.935134
            2021                                           39.658398
            2022                                           39.434854
            2023                                           39.187762

indicator          Population ages 0-14, male  \
country     years
Afghanistan 1961                    1947890.0
            1962                    1994211.0
            1963                    2046157.0
            1964                    2102926.0
            1965                    2163898.0
...                                       ...
Zimbabwe    2019                    3264895.0
            2020                    3292602.0
            2021                    3326229.0
            2022                    3363668.0
            2023                    3398136.0

indicator          Population ages 0-14, male (% of male population)  \
country     years
Afghanistan 1961                                           40.787655
            1962                                           40.973197
            1963                                           41.222394
            1964                                           41.515383
            1965                                           41.828276
...                                                              ...
Zimbabwe    2019                                           45.073806
            2020                                           44.672175
            2021                                           44.317334
            2022                                           44.011413
            2023                                           43.672594

indicator          Population ages 0-14, total  \
country     years
Afghanistan 1961                     3872549.0
            1962                     3960460.0
            1963                     4056546.0
            1964                     4162207.0
            1965                     4279578.0
...                                        ...
Zimbabwe    2019                     6496785.0
            2020                     6549831.0
            2021                     6614596.0
            2022                     6686582.0
            2023                     6752564.0

indicator          Population ages 00-04, female (% of female population)  \
country     years
Afghanistan 1961                                           17.680508
            1962                                           17.763723
            1963                                           17.849159
            1964                                           17.934117
            1965                                           18.017041
...                                                              ...
Zimbabwe    2019                                           13.956034
            2020                                           13.672596
            2021                                           13.495432
            2022                                           13.409738
            2023                                           13.362470

indicator          Population ages 00-04, male (% of male population)  \
country     years
Afghanistan 1961                                           16.748407
            1962                                           16.890811
            1963                                           17.033495
            1964                                           17.173779
            1965                                           17.309758
...                                                              ...
Zimbabwe    2019                                           15.681502
            2020                                           15.354135
            2021                                           15.142918
            2022                                           15.027098
            2023                                           14.949010

indicator          Population ages 05-09, female (% of female population)  \
country     years
Afghanistan 1961                                           13.532977
            1962                                           13.611833
            1963                                           13.686587
            1964                                           13.761375
            1965                                           13.835255
...                                                              ...
Zimbabwe    2019                                           14.199908
            2020                                           14.027493
            2021                                           13.712540
            2022                                           13.323461
            2023                                           12.931413

indicator          Population ages 05-09, male (% of male population)  ...  \
country     years                                                      ...
Afghanistan 1961                                           12.826068   ...
            1962                                           12.952211   ...
            1963                                           13.072883   ...
            1964                                           13.191123   ...
            1965                                           13.306049   ...
...                                                              ...   ...
Zimbabwe    2019                                           15.893418   ...
            2020                                           15.682738   ...
            2021                                           15.314746   ...
            2022                                           14.863275   ...
            2023                                           14.409036   ...

indicator          Population ages 65 and above, total  \
country     years
Afghanistan 1961                              258856.0
            1962                              262649.0
            1963                              266530.0
            1964                              270658.0
            1965                              275154.0
...                                                ...
Zimbabwe    2019                              539727.0
            2020                              556122.0
            2021                              568379.0
            2022                              579808.0
            2023                              591264.0

indicator          Population ages 65-69, female (% of female population)  \
country     years
Afghanistan 1961                                            1.310326
            1962                                            1.305051
            1963                                            1.299317
            1964                                            1.293372
            1965                                            1.287469
...                                                              ...
Zimbabwe    2019                                            1.725352
            2020                                            1.732029
            2021                                            1.718713
            2022                                            1.691221
            2023                                            1.650384

indicator          Population ages 65-69, male (% of male population)  \
country     years
Afghanistan 1961                                            1.425136
            1962                                            1.398324
            1963                                            1.370741
            1964                                            1.347353
            1965                                            1.329193
...                                                              ...
Zimbabwe    2019                                            1.442919
            2020                                            1.420226
            2021                                            1.379358
            2022                                            1.331850
            2023                                            1.279692

indicator          Population ages 70-74, female (% of female population)  \
country     years
Afghanistan 1961                                            0.805887
            1962                                            0.803893
            1963                                            0.802343
            1964                                            0.801164
            1965                                            0.800129
...                                                              ...
Zimbabwe    2019                                            1.010205
            2020                                            1.072398
            2021                                            1.129590
            2022                                            1.186102
            2023                                            1.246523

indicator          Population ages 70-74, male (% of male population)  \
country     years
Afghanistan 1961                                            0.875571
            1962                                            0.871112
            1963                                            0.866249
            1964                                            0.858952
            1965                                            0.849102
...                                                              ...
Zimbabwe    2019                                            0.827148
            2020                                            0.867794
            2021                                            0.901321
            2022                                            0.933359
            2023                                            0.965360

indicator          Population ages 75-79, female (% of female population)  \
country     years
Afghanistan 1961                                            0.401136
            1962                                            0.402762
            1963                                            0.403779
            1964                                            0.404304
            1965                                            0.404671
...                                                              ...
Zimbabwe    2019                                            0.609180
            2020                                            0.626289
            2021                                            0.639722
            2022                                            0.651339
            2023                                            0.660686

indicator          Population ages 75-79, male (% of male population)  \
country     years
Afghanistan 1961                                            0.427593
            1962                                            0.426341
            1963                                            0.424753
            1964                                            0.423203
            1965                                            0.421695
...                                                              ...
Zimbabwe    2019                                            0.468472
            2020                                            0.472778
            2021                                            0.474027
            2022                                            0.475669
            2023                                            0.477012

indicator          Population ages 80 and above, female (% of female population)  \
country     years
Afghanistan 1961                                            0.180730
            1962                                            0.184614
            1963                                            0.188341
            1964                                            0.191792
            1965                                            0.194953
...                                                              ...
Zimbabwe    2019                                            0.575117
            2020                                            0.569082
            2021                                            0.560137
            2022                                            0.558344
            2023                                            0.567110

indicator          Population ages 80 and above, male (% of male population)  \
country     years
Afghanistan 1961                                            0.184476
            1962                                            0.187031
            1963                                            0.189304
            1964                                            0.191248
            1965                                            0.192866
...                                                              ...
Zimbabwe    2019                                            0.368326
            2020                                            0.358180
            2021                                            0.345920
            2022                                            0.339480
            2023                                            0.339182

indicator          Population, total
country     years
Afghanistan 1961           9214083.0
            1962           9404406.0
            1963           9604487.0
            1964           9814318.0
            1965          10036008.0
...                              ...
Zimbabwe    2019          15271368.0
            2020          15526888.0
            2021          15797210.0
            2022          16069056.0
            2023          16340822.0

[13671 rows x 53 columns]

In [64]:
new_df.columns

Index(['Population ages 0-14 (% of total population)',
       'Population ages 0-14, female',
       'Population ages 0-14, female (% of female population)',
       'Population ages 0-14, male',
       'Population ages 0-14, male (% of male population)',
       'Population ages 0-14, total',
       'Population ages 00-04, female (% of female population)',
       'Population ages 00-04, male (% of male population)',
       'Population ages 05-09, female (% of female population)',
       'Population ages 05-09, male (% of male population)',
       'Population ages 10-14, female (% of female population)',
       'Population ages 10-14, male (% of male population)',
       'Population ages 15-19, female (% of female population)',
       'Population ages 15-19, male (% of male population)',
       'Population ages 15-64 (% of total population)',
       'Population ages 15-64, female',
       'Population ages 15-64, female (% of female population)',
       'Population ages 15-64, male',
       'Population ages 15-64, male (% of male population)',
       'Population ages 15-64, total',
       'Population ages 20-24, female (% of female population)',
       'Population ages 20-24, male (% of male population)',
       'Population ages 25-29, female (% of female population)',
       'Population ages 25-29, male (% of male population)',
       'Population ages 30-34, female (% of female population)',
       'Population ages 30-34, male (% of male population)',
       'Population ages 35-39, female (% of female population)',
       'Population ages 35-39, male (% of male population)',
       'Population ages 40-44, female (% of female population)',
       'Population ages 40-44, male (% of male population)',
       'Population ages 45-49, female (% of female population)',
       'Population ages 45-49, male (% of male population)',
       'Population ages 50-54, female (% of female population)',
       'Population ages 50-54, male (% of male population)',
       'Population ages 55-59, female (% of female population)',
       'Population ages 55-59, male (% of male population)',
       'Population ages 60-64, female (% of female population)',
       'Population ages 60-64, male (% of male population)',
       'Population ages 65 and above (% of total population)',
       'Population ages 65 and above, female',
       'Population ages 65 and above, female (% of female population)',
       'Population ages 65 and above, male',
       'Population ages 65 and above, male (% of male population)',
       'Population ages 65 and above, total',
       'Population ages 65-69, female (% of female population)',
       'Population ages 65-69, male (% of male population)',
       'Population ages 70-74, female (% of female population)',
       'Population ages 70-74, male (% of male population)',
       'Population ages 75-79, female (% of female population)',
       'Population ages 75-79, male (% of male population)',
       'Population ages 80 and above, female (% of female population)',
       'Population ages 80 and above, male (% of male population)',
       'Population, total'],
      dtype='object', name='indicator')

In [65]:
# cumulate data for male and female for each segment

new_df['Population ages 00-04, (% of population)'] = new_df['Population ages 00-04, male (% of male population)'] + new_df['Population ages 00-04, female (% of female population)']
new_df['Population ages 05-09, (% of population)'] = new_df['Population ages 05-09, male (% of male population)'] + new_df['Population ages 05-09, female (% of female population)']
new_df['Population ages 10-14, (% of population)'] = new_df['Population ages 10-14, male (% of male population)'] + new_df['Population ages 10-14, female (% of female population)']
new_df['Population ages 15-19, (% of population)'] = new_df['Population ages 15-19, male (% of male population)'] + new_df['Population ages 15-19, female (% of female population)']
new_df['Population ages 20-24, (% of population)'] = new_df['Population ages 20-24, male (% of male population)'] + new_df['Population ages 20-24, female (% of female population)']
new_df['Population ages 25-29, (% of population)'] = new_df['Population ages 25-29, male (% of male population)'] + new_df['Population ages 25-29, female (% of female population)']
new_df['Population ages 30-34, (% of population)'] = new_df['Population ages 30-34, male (% of male population)'] + new_df['Population ages 30-34, female (% of female population)']
new_df['Population ages 35-39, (% of population)'] = new_df['Population ages 35-39, male (% of male population)'] + new_df['Population ages 35-39, female (% of female population)']
new_df['Population ages 40-44, (% of population)'] = new_df['Population ages 40-44, male (% of male population)'] + new_df['Population ages 40-44, female (% of female population)']
new_df['Population ages 45-49, (% of population)'] = new_df['Population ages 45-49, male (% of male population)'] + new_df['Population ages 45-49, female (% of female population)']
new_df['Population ages 50-54, (% of population)'] = new_df['Population ages 50-54, male (% of male population)'] + new_df['Population ages 50-54, female (% of female population)']
new_df['Population ages 55-59, (% of population)'] = new_df['Population ages 55-59, male (% of male population)'] + new_df['Population ages 55-59, female (% of female population)']
new_df['Population ages 60-64, (% of population)'] = new_df['Population ages 60-64, male (% of male population)'] + new_df['Population ages 60-64, female (% of female population)']
new_df['Population ages 65-69, (% of population)'] = new_df['Population ages 65-69, male (% of male population)'] + new_df['Population ages 65-69, female (% of female population)']
new_df['Population ages 70-74, (% of population)'] = new_df['Population ages 70-74, male (% of male population)'] + new_df['Population ages 70-74, female (% of female population)']
new_df['Population ages 75-79, (% of population)'] = new_df['Population ages 75-79, male (% of male population)'] + new_df['Population ages 75-79, female (% of female population)']
new_df['Population ages 80 and above, (% of population)'] = new_df['Population ages 80 and above, male (% of male population)'] + new_df['Population ages 80 and above, female (% of female population)']

In [66]:
## drop former indicators

new_df = new_df.drop(columns=['Population ages 0-14 (% of total population)',
       'Population ages 0-14, female',
       'Population ages 0-14, female (% of female population)',
       'Population ages 0-14, male',
       'Population ages 0-14, male (% of male population)',
       'Population ages 0-14, total',
       'Population ages 00-04, female (% of female population)',
       'Population ages 00-04, male (% of male population)',
       'Population ages 05-09, female (% of female population)',
       'Population ages 05-09, male (% of male population)',
       'Population ages 10-14, female (% of female population)',
       'Population ages 10-14, male (% of male population)',
       'Population ages 15-19, female (% of female population)',
       'Population ages 15-19, male (% of male population)',
       'Population ages 15-64 (% of total population)',
       'Population ages 15-64, female',
       'Population ages 15-64, female (% of female population)',
       'Population ages 15-64, male',
       'Population ages 15-64, male (% of male population)',
       'Population ages 15-64, total',
       'Population ages 20-24, female (% of female population)',
       'Population ages 20-24, male (% of male population)',
       'Population ages 25-29, female (% of female population)',
       'Population ages 25-29, male (% of male population)',
       'Population ages 30-34, female (% of female population)',
       'Population ages 30-34, male (% of male population)',
       'Population ages 35-39, female (% of female population)',
       'Population ages 35-39, male (% of male population)',
       'Population ages 40-44, female (% of female population)',
       'Population ages 40-44, male (% of male population)',
       'Population ages 45-49, female (% of female population)',
       'Population ages 45-49, male (% of male population)',
       'Population ages 50-54, female (% of female population)',
       'Population ages 50-54, male (% of male population)',
       'Population ages 55-59, female (% of female population)',
       'Population ages 55-59, male (% of male population)',
       'Population ages 60-64, female (% of female population)',
       'Population ages 60-64, male (% of male population)',
       'Population ages 65 and above (% of total population)',
       'Population ages 65 and above, female',
       'Population ages 65 and above, female (% of female population)',
       'Population ages 65 and above, male',
       'Population ages 65 and above, male (% of male population)',
       'Population ages 65 and above, total',
       'Population ages 65-69, female (% of female population)',
       'Population ages 65-69, male (% of male population)',
       'Population ages 70-74, female (% of female population)',
       'Population ages 70-74, male (% of male population)',
       'Population ages 75-79, female (% of female population)',
       'Population ages 75-79, male (% of male population)',
       'Population ages 80 and above, female (% of female population)',
       'Population ages 80 and above, male (% of male population)'])

In [67]:
new_df.columns

Index(['Population, total', 'Population ages 00-04, (% of population)',
       'Population ages 05-09, (% of population)',
       'Population ages 10-14, (% of population)',
       'Population ages 15-19, (% of population)',
       'Population ages 20-24, (% of population)',
       'Population ages 25-29, (% of population)',
       'Population ages 30-34, (% of population)',
       'Population ages 35-39, (% of population)',
       'Population ages 40-44, (% of population)',
       'Population ages 45-49, (% of population)',
       'Population ages 50-54, (% of population)',
       'Population ages 55-59, (% of population)',
       'Population ages 60-64, (% of population)',
       'Population ages 65-69, (% of population)',
       'Population ages 70-74, (% of population)',
       'Population ages 75-79, (% of population)',
       'Population ages 80 and above, (% of population)'],
      dtype='object', name='indicator')

In [68]:
df_population = new_df.reset_index()
new_df.columns

Index(['Population, total', 'Population ages 00-04, (% of population)',
       'Population ages 05-09, (% of population)',
       'Population ages 10-14, (% of population)',
       'Population ages 15-19, (% of population)',
       'Population ages 20-24, (% of population)',
       'Population ages 25-29, (% of population)',
       'Population ages 30-34, (% of population)',
       'Population ages 35-39, (% of population)',
       'Population ages 40-44, (% of population)',
       'Population ages 45-49, (% of population)',
       'Population ages 50-54, (% of population)',
       'Population ages 55-59, (% of population)',
       'Population ages 60-64, (% of population)',
       'Population ages 65-69, (% of population)',
       'Population ages 70-74, (% of population)',
       'Population ages 75-79, (% of population)',
       'Population ages 80 and above, (% of population)'],
      dtype='object', name='indicator')

In [69]:
## if needed unpivot the DF

# df_population = pd.melt(
#                     new_df, 
#                     id_vars=['country', 'years'],
#                     value_vars=['Population ages 00-04, (% of population)',
#                                 'Population ages 05-09, (% of population)',
#                                 'Population ages 10-14, (% of population)',
#                                 'Population ages 15-19, (% of population)',
#                                 'Population ages 20-24, (% of population)',
#                                 'Population ages 25-29, (% of population)',
#                                 'Population ages 30-34, (% of population)',
#                                 'Population ages 35-39, (% of population)',
#                                 'Population ages 40-44, (% of population)',
#                                 'Population ages 45-49, (% of population)',
#                                 'Population ages 50-54, (% of population)',
#                                 'Population ages 55-59, (% of population)',
#                                 'Population ages 60-64, (% of population)',
#                                 'Population ages 65-69, (% of population)',
#                                 'Population ages 70-74, (% of population)',
#                                 'Population ages 75-79, (% of population)',
#                                 'Population ages 80 and above, (% of population)'
#                                 ],
#                      var_name='indicator' ,           
#                      value_name='Value' )
# df_population = df_population.reset_index()
df_population.head()

indicator,country,years,"Population, total","Population ages 00-04, (% of population)","Population ages 05-09, (% of population)","Population ages 10-14, (% of population)","Population ages 15-19, (% of population)","Population ages 20-24, (% of population)","Population ages 25-29, (% of population)","Population ages 30-34, (% of population)","Population ages 35-39, (% of population)","Population ages 40-44, (% of population)","Population ages 45-49, (% of population)","Population ages 50-54, (% of population)","Population ages 55-59, (% of population)","Population ages 60-64, (% of population)","Population ages 65-69, (% of population)","Population ages 70-74, (% of population)","Population ages 75-79, (% of population)","Population ages 80 and above, (% of population)"
0,Afghanistan,1961,9214083.0,34.428915,26.359045,23.363518,20.628007,17.700997,15.283814,13.210589,11.144825,9.299025,7.726049,6.289341,5.095110,3.859910,2.735462,1.681458,0.828729,0.365206
1,Afghanistan,1962,9404406.0,34.654533,26.564044,23.089889,20.791671,17.621578,15.264896,13.157597,11.151110,9.279892,7.702293,6.263756,5.042119,3.837494,2.703375,1.675005,0.829103,0.371645
2,Afghanistan,1963,9604487.0,34.882654,26.759469,22.900307,20.869184,17.561264,15.247672,13.094646,11.152464,9.260933,7.676416,6.245131,4.986267,3.818766,2.670058,1.668591,0.828532,0.377645
3,Afghanistan,1964,9814318.0,35.107896,26.952498,22.818278,20.821519,17.557706,15.205975,13.031241,11.137576,9.245795,7.650622,6.226406,4.936880,3.796219,2.640725,1.660116,0.827507,0.383040
4,Afghanistan,1965,10036008.0,35.326800,27.141304,22.868356,20.621078,17.619636,15.139388,12.968674,11.104902,9.233071,7.626674,6.205011,4.897032,3.767998,2.616662,1.649230,0.826366,0.387818

## save as csv

In [70]:
path = f'../Resources_Output/macro_economic_data_population_wide.csv'
df_population.to_csv(path)

# Report
print(f'file printed for ')
print(f'Years :  {lib_years}')
print(f'number of Countries : {lib_countries}  ')
print(f'Number of Indicators : {lib_indicators} ')

file printed for
Years :  from_1960
number of Countries : 217
Number of Indicators : 53